# Generated by Django 5.2 on 2025-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='teacher_images/'),
            preserve_default=False,
        ),
    ]
